# Generated by Django 5.0.14 on 2026-07-27 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fathered_children', to='family_tree.familymember'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='joined_by_marriage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymember',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mothered_children', to='family_tree.familymember'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_of', to='family_tree.familymember'),
        ),
    ]
