# Generated by Django 5.0.14 on 2026-07-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0004_remove_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
