# Generated by Django 5.0.14 on 2026-08-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0005_alter_familymember_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='is_deceased',
            field=models.BooleanField(default=False, help_text='Marked deceased. Independent of date_of_death, which is often unknown.'),
        ),
    ]
