# Generated by Django 5.0.14 on 2026-06-19 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnniversaryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='anniversary/')),
                ('event_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Anniversary Event',
                'verbose_name_plural': 'Anniversary Events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='AnniversaryReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_role', models.CharField(blank=True, max_length=200)),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='anniversary/reflections/')),
                ('quote_text', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='anniversary.anniversaryevent')),
            ],
            options={
                'verbose_name': 'Anniversary Reflection',
                'verbose_name_plural': 'Anniversary Reflections',
            },
        ),
    ]
